"""buat table dosen

Revision ID: 1e6568cd8e01
Revises: d545a8ab9f6b
Create Date: 2025-07-16 07:52:14.218083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6568cd8e01'
down_revision = 'd545a8ab9f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nidn', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dosen')
    # ### end Alembic commands ###
