"""buat table mahasiswa

Revision ID: b9241ad114e8
Revises: 1e6568cd8e01
Create Date: 2025-07-16 08:41:18.307130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9241ad114e8'
down_revision = '1e6568cd8e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nim', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('dosen_one', sa.Integer(), nullable=True),
    sa.Column('dosen_two', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_one'], ['dosen.id'], ),
    sa.ForeignKeyConstraint(['dosen_two'], ['dosen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
