"""cascade in mahasiswa

Revision ID: d1ce887c8570
Revises: b9241ad114e8
Create Date: 2025-07-16 16:05:16.015620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ce887c8570'
down_revision = 'b9241ad114e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mahasiswa_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('mahasiswa_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dosen', ['dosen_two'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'dosen', ['dosen_one'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mahasiswa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mahasiswa_ibfk_1'), 'dosen', ['dosen_one'], ['id'])
        batch_op.create_foreign_key(batch_op.f('mahasiswa_ibfk_2'), 'dosen', ['dosen_two'], ['id'])

    # ### end Alembic commands ###
